name: Weather App

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    env:
      RELEASE_VERSION: "1.0.0"
      REPO_URL: https://github.com/${{ github.repository }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ghcr.io/${{ github.repository }}:latest
          push: true
